package com.example.movieapp.utils

const val SPLASH_DISPLAY_LENGTH: Long = 1000
const val LOADING_LENGTH: Long = 500
const val BASE_URL = "https://api.themoviedb.org/3/"
const val API_KEY = "176fa03204ca73806a14b489cfc31842"
const val BASE_URL_IMG = "https://image.tmdb.org/t/p/w500"
const val BASE_URL_VIDEO = "https://www.youtube.com/watch?v="
const val SESSION_ID = "0c00ab041b1ed89db5d08867f7ee0d72a3a0d87e"
const val MOVIE = "movie"

const val ID_MOVIE = "id_movie"
const val ID_CAST = "id_cast"


const val ADMIN = "admin_account"
const val USER = "user_account"
const val ACCOUNT = "account"
const val USER_NAME = "user_name"
const val PHONE_NUMBER = "phone_number"
const val PRODUCT = "product"
const val NAME_PRODUCT = "name_product"
const val ADIDAS = "Adidas"
const val NIKE = "Nike"
const val CONVERSE = "Converse"
const val PUMA = "Puma"
const val JORDAN = "Jordan"
const val URL_AVATAR = "url_avatar"
const val PRODUCT_MODEL = "product_model"
const val TYPE_ACCOUNT = "type_account"
const val DETAIL_PRODUCT = "detail_product"
const val USER_CART = "user_cart"
const val CART_PRODUCT_MODEL = "cart_product_model"
const val TYPE = "type"
const val ORDER_SUCCESS = "order_success"
const val NEW_ORDER = "new_order"
const val ORDER_CONFIRM = "order_confirm"
const val ORDER_DELIVERING = "order_delivering"
const val ORDER_COMPLETED = "order_completed"
const val ORDER_CANCELED = "order_canceled"
const val ORDER = "order"
